title: Networking Conference Deadlines
description: Countdowns to top networking conference deadlines
author: Grupo de Teleinformática e Automação

domain: "gta.ufrj.br/~gustavo/deadlines"
baseurl: ""

twitter_hashtag: networking
github_username: gFrancoCamilo
github_repo: networking-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
